"""update orders table

Revision ID: 593dfcc40042
Revises: 3d5bc4e93c24
Create Date: 2026-05-04 11:50:28.476018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593dfcc40042'
down_revision: Union[str, Sequence[str], None] = '3d5bc4e93c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
